[package]
name = "gol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ca-formats = "0.3.5"
ca-rules = "0.3.5"
godot = "0.4.0"
rand = "0.9.2"
rayon = "1.11.0"
[lib]
crate-type = ["cdylib"]
